// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element

import 'data_model.dart' as p0;
import 'models/entities/address.dart' as p1;
import 'models/entities/address_type.dart' as p2;
import 'models/entities/attributes.dart' as p3;
import 'models/entities/beneficiary_type.dart' as p4;
import 'models/entities/blood_group.dart' as p5;
import 'models/entities/boundary.dart' as p6;
import 'models/entities/document.dart' as p7;
import 'models/entities/facility.dart' as p8;
import 'models/entities/gender.dart' as p9;
import 'models/entities/household.dart' as p10;
import 'models/entities/household_member.dart' as p11;
import 'models/entities/household_member_relationship.dart' as p12;
import 'models/entities/household_type.dart' as p13;
import 'models/entities/identifier.dart' as p14;
import 'models/entities/identifier_types.dart' as p15;
import 'models/entities/individual.dart' as p16;
import 'models/entities/locality.dart' as p17;
import 'models/entities/name.dart' as p18;
import 'models/entities/pgr_application_status.dart' as p19;
import 'models/entities/product.dart' as p20;
import 'models/entities/product_variant.dart' as p21;
import 'models/entities/project.dart' as p22;
import 'models/entities/project_beneficiary.dart' as p23;
import 'models/entities/project_facility.dart' as p24;
import 'models/entities/project_product_variant.dart' as p25;
import 'models/entities/project_resource.dart' as p26;
import 'models/entities/project_staff.dart' as p27;
import 'models/entities/project_type.dart' as p28;
import 'models/entities/referral.dart' as p29;
import 'models/entities/side_effect.dart' as p30;
import 'models/entities/stock.dart' as p31;
import 'models/entities/stock_reconciliation.dart' as p32;
import 'models/entities/target.dart' as p33;
import 'models/entities/task.dart' as p34;
import 'models/entities/task_resource.dart' as p35;
import 'models/entities/unique_id_pool.dart' as p36;
import 'models/entities/user.dart' as p37;
import 'models/entities/user_action.dart' as p38;
import 'models/oplog/oplog_entry.dart' as p39;

void initializeMappers() {
  p0.EntityModelMapper.ensureInitialized();
  p0.EntitySearchModelMapper.ensureInitialized();
  p0.AdditionalFieldsMapper.ensureInitialized();
  p0.AdditionalFieldMapper.ensureInitialized();
  p0.ClientAuditDetailsMapper.ensureInitialized();
  p0.AuditDetailsMapper.ensureInitialized();
  p1.AddressSearchModelMapper.ensureInitialized();
  p1.AddressModelMapper.ensureInitialized();
  p1.AddressAdditionalFieldsMapper.ensureInitialized();
  p2.AddressTypeMapper.ensureInitialized();
  p3.AttributesSearchModelMapper.ensureInitialized();
  p3.AttributesModelMapper.ensureInitialized();
  p3.AttributesAdditionalFieldsMapper.ensureInitialized();
  p4.BeneficiaryTypeMapper.ensureInitialized();
  p5.BloodGroupMapper.ensureInitialized();
  p6.BoundarySearchModelMapper.ensureInitialized();
  p6.BoundaryModelMapper.ensureInitialized();
  p7.DocumentSearchModelMapper.ensureInitialized();
  p7.DocumentModelMapper.ensureInitialized();
  p7.DocumentAdditionalFieldsMapper.ensureInitialized();
  p8.FacilitySearchModelMapper.ensureInitialized();
  p8.FacilityModelMapper.ensureInitialized();
  p8.FacilityAdditionalFieldsMapper.ensureInitialized();
  p9.GenderMapper.ensureInitialized();
  p10.HouseholdSearchModelMapper.ensureInitialized();
  p10.HouseholdModelMapper.ensureInitialized();
  p10.HouseholdAdditionalFieldsMapper.ensureInitialized();
  p11.HouseholdMemberSearchModelMapper.ensureInitialized();
  p11.HouseholdMemberModelMapper.ensureInitialized();
  p11.HouseholdMemberAdditionalFieldsMapper.ensureInitialized();
  p12.HouseholdMemberRelationShipSearchModelMapper.ensureInitialized();
  p12.HouseholdMemberRelationShipModelMapper.ensureInitialized();
  p12.HouseholdMemberRelationShipAdditionalFieldsMapper.ensureInitialized();
  p13.HouseholdTypeMapper.ensureInitialized();
  p14.IdentifierSearchModelMapper.ensureInitialized();
  p14.IdentifierModelMapper.ensureInitialized();
  p14.IdentifierAdditionalFieldsMapper.ensureInitialized();
  p15.IdentifierTypesMapper.ensureInitialized();
  p16.IndividualSearchModelMapper.ensureInitialized();
  p16.IndividualModelMapper.ensureInitialized();
  p16.IndividualAdditionalFieldsMapper.ensureInitialized();
  p17.LocalitySearchModelMapper.ensureInitialized();
  p17.LocalityModelMapper.ensureInitialized();
  p17.LocalityAdditionalFieldsMapper.ensureInitialized();
  p18.NameSearchModelMapper.ensureInitialized();
  p18.NameModelMapper.ensureInitialized();
  p18.NameAdditionalFieldsMapper.ensureInitialized();
  p19.PgrServiceApplicationStatusMapper.ensureInitialized();
  p20.ProductSearchModelMapper.ensureInitialized();
  p20.ProductModelMapper.ensureInitialized();
  p20.ProductAdditionalFieldsMapper.ensureInitialized();
  p21.ProductVariantSearchModelMapper.ensureInitialized();
  p21.ProductVariantModelMapper.ensureInitialized();
  p21.ProductVariantAdditionalFieldsMapper.ensureInitialized();
  p22.ProjectSearchModelMapper.ensureInitialized();
  p22.ProjectModelMapper.ensureInitialized();
  p22.ProjectAdditionalFieldsMapper.ensureInitialized();
  p22.ProjectAdditionalDetailsMapper.ensureInitialized();
  p23.ProjectBeneficiarySearchModelMapper.ensureInitialized();
  p23.ProjectBeneficiaryModelMapper.ensureInitialized();
  p23.ProjectBeneficiaryAdditionalFieldsMapper.ensureInitialized();
  p24.ProjectFacilitySearchModelMapper.ensureInitialized();
  p24.ProjectFacilityModelMapper.ensureInitialized();
  p24.ProjectFacilityAdditionalFieldsMapper.ensureInitialized();
  p25.ProjectProductVariantSearchModelMapper.ensureInitialized();
  p25.ProjectProductVariantModelMapper.ensureInitialized();
  p25.ProjectProductVariantAdditionalFieldsMapper.ensureInitialized();
  p26.ProjectResourceSearchModelMapper.ensureInitialized();
  p26.ProjectResourceModelMapper.ensureInitialized();
  p26.ProjectResourceAdditionalFieldsMapper.ensureInitialized();
  p27.ProjectStaffSearchModelMapper.ensureInitialized();
  p27.ProjectStaffModelMapper.ensureInitialized();
  p27.ProjectStaffAdditionalFieldsMapper.ensureInitialized();
  p28.ProjectTypeModelMapper.ensureInitialized();
  p28.ProjectTypeAdditionalFieldsMapper.ensureInitialized();
  p28.ProjectCycleMapper.ensureInitialized();
  p28.ProjectCycleDeliveryMapper.ensureInitialized();
  p28.DeliveryDoseCriteriaMapper.ensureInitialized();
  p28.DeliveryProductVariantMapper.ensureInitialized();
  p29.ReferralSearchModelMapper.ensureInitialized();
  p29.ReferralModelMapper.ensureInitialized();
  p29.ReferralAdditionalFieldsMapper.ensureInitialized();
  p30.SideEffectSearchModelMapper.ensureInitialized();
  p30.SideEffectModelMapper.ensureInitialized();
  p30.SideEffectAdditionalFieldsMapper.ensureInitialized();
  p31.StockSearchModelMapper.ensureInitialized();
  p31.StockModelMapper.ensureInitialized();
  p31.StockAdditionalFieldsMapper.ensureInitialized();
  p32.StockReconciliationSearchModelMapper.ensureInitialized();
  p32.StockReconciliationModelMapper.ensureInitialized();
  p32.StockReconciliationAdditionalFieldsMapper.ensureInitialized();
  p33.TargetSearchModelMapper.ensureInitialized();
  p33.TargetModelMapper.ensureInitialized();
  p33.TargetAdditionalFieldsMapper.ensureInitialized();
  p34.TaskSearchModelMapper.ensureInitialized();
  p34.TaskModelMapper.ensureInitialized();
  p34.TaskAdditionalFieldsMapper.ensureInitialized();
  p35.TaskResourceSearchModelMapper.ensureInitialized();
  p35.TaskResourceModelMapper.ensureInitialized();
  p35.TaskResourceAdditionalFieldsMapper.ensureInitialized();
  p36.UniqueIdPoolSearchModelMapper.ensureInitialized();
  p36.UniqueIdPoolModelMapper.ensureInitialized();
  p36.UniqueIdPoolAdditionalFieldsMapper.ensureInitialized();
  p36.UniqueIdSearchResponseMapper.ensureInitialized();
  p37.UserSearchModelMapper.ensureInitialized();
  p37.UserModelMapper.ensureInitialized();
  p37.UserAdditionalFieldsMapper.ensureInitialized();
  p38.UserActionSearchModelMapper.ensureInitialized();
  p38.UserActionModelMapper.ensureInitialized();
  p38.UserActionAdditionalFieldsMapper.ensureInitialized();
  p39.OpLogEntryMapper.ensureInitialized();
  p39.AdditionalIdMapper.ensureInitialized();
  p39.DataOperationMapper.ensureInitialized();
  p39.ApiOperationMapper.ensureInitialized();
}
