// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element

import 'data_model.dart' as p0;
import 'models/entities/address.dart' as p1;
import 'models/entities/address_type.dart' as p2;
import 'models/entities/attributes.dart' as p3;
import 'models/entities/beneficiary_type.dart' as p4;
import 'models/entities/blood_group.dart' as p5;
import 'models/entities/boundary.dart' as p6;
import 'models/entities/document.dart' as p7;
import 'models/entities/facility.dart' as p8;
import 'models/entities/gender.dart' as p9;
import 'models/entities/household_type.dart' as p10;
import 'models/entities/identifier.dart' as p11;
import 'models/entities/identifier_types.dart' as p12;
import 'models/entities/individual.dart' as p13;
import 'models/entities/locality.dart' as p14;
import 'models/entities/name.dart' as p15;
import 'models/entities/pgr_application_status.dart' as p16;
import 'models/entities/product.dart' as p17;
import 'models/entities/product_variant.dart' as p18;
import 'models/entities/project.dart' as p19;
import 'models/entities/project_facility.dart' as p20;
import 'models/entities/project_product_variant.dart' as p21;
import 'models/entities/project_resource.dart' as p22;
import 'models/entities/project_staff.dart' as p23;
import 'models/entities/project_type.dart' as p24;
import 'models/entities/target.dart' as p25;
import 'models/entities/user.dart' as p26;
import 'models/entities/user_action.dart' as p27;
import 'models/oplog/oplog_entry.dart' as p28;

void initializeMappers() {
  p0.EntityModelMapper.ensureInitialized();
  p0.EntitySearchModelMapper.ensureInitialized();
  p0.AdditionalFieldsMapper.ensureInitialized();
  p0.AdditionalFieldMapper.ensureInitialized();
  p0.ClientAuditDetailsMapper.ensureInitialized();
  p0.AuditDetailsMapper.ensureInitialized();
  p1.AddressSearchModelMapper.ensureInitialized();
  p1.AddressModelMapper.ensureInitialized();
  p1.AddressAdditionalFieldsMapper.ensureInitialized();
  p2.AddressTypeMapper.ensureInitialized();
  p3.AttributesSearchModelMapper.ensureInitialized();
  p3.AttributesModelMapper.ensureInitialized();
  p3.AttributesAdditionalFieldsMapper.ensureInitialized();
  p4.BeneficiaryTypeMapper.ensureInitialized();
  p5.BloodGroupMapper.ensureInitialized();
  p6.BoundarySearchModelMapper.ensureInitialized();
  p6.BoundaryModelMapper.ensureInitialized();
  p7.DocumentSearchModelMapper.ensureInitialized();
  p7.DocumentModelMapper.ensureInitialized();
  p7.DocumentAdditionalFieldsMapper.ensureInitialized();
  p8.FacilitySearchModelMapper.ensureInitialized();
  p8.FacilityModelMapper.ensureInitialized();
  p8.FacilityAdditionalFieldsMapper.ensureInitialized();
  p9.GenderMapper.ensureInitialized();
  p10.HouseholdTypeMapper.ensureInitialized();
  p11.IdentifierSearchModelMapper.ensureInitialized();
  p11.IdentifierModelMapper.ensureInitialized();
  p11.IdentifierAdditionalFieldsMapper.ensureInitialized();
  p12.IdentifierTypesMapper.ensureInitialized();
  p13.IndividualSearchModelMapper.ensureInitialized();
  p13.IndividualModelMapper.ensureInitialized();
  p13.IndividualAdditionalFieldsMapper.ensureInitialized();
  p14.LocalitySearchModelMapper.ensureInitialized();
  p14.LocalityModelMapper.ensureInitialized();
  p14.LocalityAdditionalFieldsMapper.ensureInitialized();
  p15.NameSearchModelMapper.ensureInitialized();
  p15.NameModelMapper.ensureInitialized();
  p15.NameAdditionalFieldsMapper.ensureInitialized();
  p16.PgrServiceApplicationStatusMapper.ensureInitialized();
  p17.ProductSearchModelMapper.ensureInitialized();
  p17.ProductModelMapper.ensureInitialized();
  p17.ProductAdditionalFieldsMapper.ensureInitialized();
  p18.ProductVariantSearchModelMapper.ensureInitialized();
  p18.ProductVariantModelMapper.ensureInitialized();
  p18.ProductVariantAdditionalFieldsMapper.ensureInitialized();
  p19.ProjectSearchModelMapper.ensureInitialized();
  p19.ProjectModelMapper.ensureInitialized();
  p19.ProjectAdditionalFieldsMapper.ensureInitialized();
  p19.ProjectAdditionalDetailsMapper.ensureInitialized();
  p20.ProjectFacilitySearchModelMapper.ensureInitialized();
  p20.ProjectFacilityModelMapper.ensureInitialized();
  p20.ProjectFacilityAdditionalFieldsMapper.ensureInitialized();
  p21.ProjectProductVariantSearchModelMapper.ensureInitialized();
  p21.ProjectProductVariantModelMapper.ensureInitialized();
  p21.ProjectProductVariantAdditionalFieldsMapper.ensureInitialized();
  p22.ProjectResourceSearchModelMapper.ensureInitialized();
  p22.ProjectResourceModelMapper.ensureInitialized();
  p22.ProjectResourceAdditionalFieldsMapper.ensureInitialized();
  p23.ProjectStaffSearchModelMapper.ensureInitialized();
  p23.ProjectStaffModelMapper.ensureInitialized();
  p23.ProjectStaffAdditionalFieldsMapper.ensureInitialized();
  p24.ProjectTypeModelMapper.ensureInitialized();
  p24.ProjectTypeAdditionalFieldsMapper.ensureInitialized();
  p24.ProjectCycleMapper.ensureInitialized();
  p24.ProjectCycleDeliveryMapper.ensureInitialized();
  p24.DeliveryDoseCriteriaMapper.ensureInitialized();
  p24.DeliveryProductVariantMapper.ensureInitialized();
  p25.TargetSearchModelMapper.ensureInitialized();
  p25.TargetModelMapper.ensureInitialized();
  p25.TargetAdditionalFieldsMapper.ensureInitialized();
  p26.UserSearchModelMapper.ensureInitialized();
  p26.UserModelMapper.ensureInitialized();
  p26.UserAdditionalFieldsMapper.ensureInitialized();
  p27.UserActionSearchModelMapper.ensureInitialized();
  p27.UserActionModelMapper.ensureInitialized();
  p27.UserActionAdditionalFieldsMapper.ensureInitialized();
  p28.OpLogEntryMapper.ensureInitialized();
  p28.AdditionalIdMapper.ensureInitialized();
  p28.DataOperationMapper.ensureInitialized();
  p28.ApiOperationMapper.ensureInitialized();
}
