// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element

import 'data_model.dart' as p0;
import 'models/entities/address.dart' as p1;
import 'models/entities/address_type.dart' as p2;
import 'models/entities/attributes.dart' as p3;
import 'models/entities/beneficiary_type.dart' as p4;
import 'models/entities/blood_group.dart' as p5;
import 'models/entities/boundary.dart' as p6;
import 'models/entities/document.dart' as p7;
import 'models/entities/face_auth_event.dart' as p8;
import 'models/entities/facility.dart' as p9;
import 'models/entities/gender.dart' as p10;
import 'models/entities/hf_referral.dart' as p11;
import 'models/entities/household.dart' as p12;
import 'models/entities/household_member.dart' as p13;
import 'models/entities/household_member_relationship.dart' as p14;
import 'models/entities/household_type.dart' as p15;
import 'models/entities/id_status.dart' as p16;
import 'models/entities/identifier.dart' as p17;
import 'models/entities/identifier_types.dart' as p18;
import 'models/entities/individual.dart' as p19;
import 'models/entities/locality.dart' as p20;
import 'models/entities/name.dart' as p21;
import 'models/entities/pgr_address.dart' as p22;
import 'models/entities/pgr_application_status.dart' as p23;
import 'models/entities/pgr_complaints.dart' as p24;
import 'models/entities/pgr_complaints_response.dart' as p25;
import 'models/entities/product.dart' as p26;
import 'models/entities/product_variant.dart' as p27;
import 'models/entities/project.dart' as p28;
import 'models/entities/project_beneficiary.dart' as p29;
import 'models/entities/project_facility.dart' as p30;
import 'models/entities/project_product_variant.dart' as p31;
import 'models/entities/project_resource.dart' as p32;
import 'models/entities/project_staff.dart' as p33;
import 'models/entities/project_type.dart' as p34;
import 'models/entities/referral.dart' as p35;
import 'models/entities/side_effect.dart' as p36;
import 'models/entities/stock.dart' as p37;
import 'models/entities/stock_reconciliation.dart' as p38;
import 'models/entities/target.dart' as p39;
import 'models/entities/task.dart' as p40;
import 'models/entities/task_resource.dart' as p41;
import 'models/entities/unique_id_pool.dart' as p42;
import 'models/entities/user.dart' as p43;
import 'models/entities/user_action.dart' as p44;
import 'models/oplog/oplog_entry.dart' as p45;

void initializeMappers() {
  p0.EntityModelMapper.ensureInitialized();
  p0.EntitySearchModelMapper.ensureInitialized();
  p0.AdditionalFieldsMapper.ensureInitialized();
  p0.AdditionalFieldMapper.ensureInitialized();
  p0.ClientAuditDetailsMapper.ensureInitialized();
  p0.AuditDetailsMapper.ensureInitialized();
  p1.AddressSearchModelMapper.ensureInitialized();
  p1.AddressModelMapper.ensureInitialized();
  p1.AddressAdditionalFieldsMapper.ensureInitialized();
  p2.AddressTypeMapper.ensureInitialized();
  p3.AttributesSearchModelMapper.ensureInitialized();
  p3.AttributesModelMapper.ensureInitialized();
  p3.AttributesAdditionalFieldsMapper.ensureInitialized();
  p4.BeneficiaryTypeMapper.ensureInitialized();
  p5.BloodGroupMapper.ensureInitialized();
  p6.BoundarySearchModelMapper.ensureInitialized();
  p6.BoundaryModelMapper.ensureInitialized();
  p7.DocumentSearchModelMapper.ensureInitialized();
  p7.DocumentModelMapper.ensureInitialized();
  p7.DocumentAdditionalFieldsMapper.ensureInitialized();
  p8.FaceAuthEventSearchModelMapper.ensureInitialized();
  p8.FaceAuthEventModelMapper.ensureInitialized();
  p8.FaceAuthEventAdditionalFieldsMapper.ensureInitialized();
  p9.FacilitySearchModelMapper.ensureInitialized();
  p9.FacilityModelMapper.ensureInitialized();
  p9.FacilityAdditionalFieldsMapper.ensureInitialized();
  p10.GenderMapper.ensureInitialized();
  p11.HFReferralSearchModelMapper.ensureInitialized();
  p11.HFReferralModelMapper.ensureInitialized();
  p11.HFReferralAdditionalFieldsMapper.ensureInitialized();
  p12.HouseholdSearchModelMapper.ensureInitialized();
  p12.HouseholdModelMapper.ensureInitialized();
  p12.HouseholdAdditionalFieldsMapper.ensureInitialized();
  p13.HouseholdMemberSearchModelMapper.ensureInitialized();
  p13.HouseholdMemberModelMapper.ensureInitialized();
  p13.HouseholdMemberAdditionalFieldsMapper.ensureInitialized();
  p14.HouseholdMemberRelationShipSearchModelMapper.ensureInitialized();
  p14.HouseholdMemberRelationShipModelMapper.ensureInitialized();
  p14.HouseholdMemberRelationShipAdditionalFieldsMapper.ensureInitialized();
  p15.HouseholdTypeMapper.ensureInitialized();
  p16.IdStatusMapper.ensureInitialized();
  p17.IdentifierSearchModelMapper.ensureInitialized();
  p17.IdentifierModelMapper.ensureInitialized();
  p17.IdentifierAdditionalFieldsMapper.ensureInitialized();
  p18.IdentifierTypesMapper.ensureInitialized();
  p19.IndividualSearchModelMapper.ensureInitialized();
  p19.IndividualModelMapper.ensureInitialized();
  p19.IndividualAdditionalFieldsMapper.ensureInitialized();
  p20.LocalitySearchModelMapper.ensureInitialized();
  p20.LocalityModelMapper.ensureInitialized();
  p20.LocalityAdditionalFieldsMapper.ensureInitialized();
  p21.NameSearchModelMapper.ensureInitialized();
  p21.NameModelMapper.ensureInitialized();
  p21.NameAdditionalFieldsMapper.ensureInitialized();
  p22.PgrAddressModelMapper.ensureInitialized();
  p22.GeoLocationMapper.ensureInitialized();
  p23.PgrServiceApplicationStatusMapper.ensureInitialized();
  p24.PgrComplaintModelMapper.ensureInitialized();
  p24.PgrComplainantModelMapper.ensureInitialized();
  p24.PgrRolesModelMapper.ensureInitialized();
  p24.PgrServiceSearchModelMapper.ensureInitialized();
  p24.PgrServiceModelMapper.ensureInitialized();
  p24.PgrWorkflowModelMapper.ensureInitialized();
  p24.PgrFiltersMapper.ensureInitialized();
  p24.PgrSearchKeysMapper.ensureInitialized();
  p24.PgrAdditionalDetailsMapper.ensureInitialized();
  p25.PgrServiceCreateResponseModelMapper.ensureInitialized();
  p25.PgrComplaintResponseModelMapper.ensureInitialized();
  p25.PgrComplainantResponseModelMapper.ensureInitialized();
  p25.PgrServiceResponseModelMapper.ensureInitialized();
  p26.ProductSearchModelMapper.ensureInitialized();
  p26.ProductModelMapper.ensureInitialized();
  p26.ProductAdditionalFieldsMapper.ensureInitialized();
  p27.ProductVariantSearchModelMapper.ensureInitialized();
  p27.ProductVariantModelMapper.ensureInitialized();
  p27.ProductVariantAdditionalFieldsMapper.ensureInitialized();
  p28.ProjectSearchModelMapper.ensureInitialized();
  p28.ProjectModelMapper.ensureInitialized();
  p28.ProjectAdditionalFieldsMapper.ensureInitialized();
  p28.ProjectAdditionalDetailsMapper.ensureInitialized();
  p29.ProjectBeneficiarySearchModelMapper.ensureInitialized();
  p29.ProjectBeneficiaryModelMapper.ensureInitialized();
  p29.ProjectBeneficiaryAdditionalFieldsMapper.ensureInitialized();
  p30.ProjectFacilitySearchModelMapper.ensureInitialized();
  p30.ProjectFacilityModelMapper.ensureInitialized();
  p30.ProjectFacilityAdditionalFieldsMapper.ensureInitialized();
  p31.ProjectProductVariantSearchModelMapper.ensureInitialized();
  p31.ProjectProductVariantModelMapper.ensureInitialized();
  p31.ProjectProductVariantAdditionalFieldsMapper.ensureInitialized();
  p32.ProjectResourceSearchModelMapper.ensureInitialized();
  p32.ProjectResourceModelMapper.ensureInitialized();
  p32.ProjectResourceAdditionalFieldsMapper.ensureInitialized();
  p33.ProjectStaffSearchModelMapper.ensureInitialized();
  p33.ProjectStaffModelMapper.ensureInitialized();
  p33.ProjectStaffAdditionalFieldsMapper.ensureInitialized();
  p34.ProjectTypeModelMapper.ensureInitialized();
  p34.ProjectTypeAdditionalFieldsMapper.ensureInitialized();
  p34.ProjectCycleMapper.ensureInitialized();
  p34.ProjectCycleDeliveryMapper.ensureInitialized();
  p34.DeliveryDoseCriteriaMapper.ensureInitialized();
  p34.DeliveryProductVariantMapper.ensureInitialized();
  p35.ReferralSearchModelMapper.ensureInitialized();
  p35.ReferralModelMapper.ensureInitialized();
  p35.ReferralAdditionalFieldsMapper.ensureInitialized();
  p36.SideEffectSearchModelMapper.ensureInitialized();
  p36.SideEffectModelMapper.ensureInitialized();
  p36.SideEffectAdditionalFieldsMapper.ensureInitialized();
  p37.StockSearchModelMapper.ensureInitialized();
  p37.StockModelMapper.ensureInitialized();
  p37.StockAdditionalFieldsMapper.ensureInitialized();
  p38.StockReconciliationSearchModelMapper.ensureInitialized();
  p38.StockReconciliationModelMapper.ensureInitialized();
  p38.StockReconciliationAdditionalFieldsMapper.ensureInitialized();
  p39.TargetSearchModelMapper.ensureInitialized();
  p39.TargetModelMapper.ensureInitialized();
  p39.TargetAdditionalFieldsMapper.ensureInitialized();
  p40.TaskSearchModelMapper.ensureInitialized();
  p40.TaskModelMapper.ensureInitialized();
  p40.TaskAdditionalFieldsMapper.ensureInitialized();
  p41.TaskResourceSearchModelMapper.ensureInitialized();
  p41.TaskResourceModelMapper.ensureInitialized();
  p41.TaskResourceAdditionalFieldsMapper.ensureInitialized();
  p42.UniqueIdPoolSearchModelMapper.ensureInitialized();
  p42.UniqueIdPoolModelMapper.ensureInitialized();
  p42.UniqueIdPoolAdditionalFieldsMapper.ensureInitialized();
  p42.UniqueIdSearchResponseMapper.ensureInitialized();
  p43.UserSearchModelMapper.ensureInitialized();
  p43.UserModelMapper.ensureInitialized();
  p43.UserAdditionalFieldsMapper.ensureInitialized();
  p44.UserActionSearchModelMapper.ensureInitialized();
  p44.UserActionModelMapper.ensureInitialized();
  p44.UserActionAdditionalFieldsMapper.ensureInitialized();
  p45.OpLogEntryMapper.ensureInitialized();
  p45.AdditionalIdMapper.ensureInitialized();
  p45.DataOperationMapper.ensureInitialized();
  p45.ApiOperationMapper.ensureInitialized();
}
