name: digit_flutter
repository: https://github.com/egovernments/health-campaign-field-worker-app

packages:
  - packages/*
  - apps/*

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  postbootstrap: melos run generate:build-runner --no-select

  test:
    run: melos exec --dir-exists="test" --fail-fast -- flutter test --no-pub --coverage
    description: Run Flutter tests for a specific package in this project.
    select-package:
      flutter: true
      dir-exists: test

  all-test:
    run: melos run test --no-select
    description: Run all Flutter tests in this project.

  analyze:
    run: melos exec -- flutter analyze .
    description: Run `dart analyze` in all packages.

  combine-coverage:
    run: melos exec -- "\$MELOS_ROOT_PATH/tools/combine_coverage.sh"
    description: Combine coverage report of all packages

  generate:coverage-report:
    run: melos exec -- genhtml \$MELOS_ROOT_PATH/coverage_report/lcov.info -o \$MELOS_ROOT_PATH/coverage_report/html
    description: Generate a coverage report using lcov.info. Requires genhtml to be installed.

  generate:build-runner:
    exec: flutter packages run build_runner build --delete-conflicting-outputs
    select-package:
      flutter: true
      depends-on: build_runner

  watch:build-runner:
    exec: flutter packages run build_runner watch
    select-package:
      flutter: true
      depends-on: build_runner

  open_report:
    run: melos exec -- melos run generate:coverage-report && open coverage_report/html/index.html

