name: digit_forms_engine
description: A dynamic form rendering engine for Flutter, built on top of the `digit_ui_components` package. It supports multi-page, configurable forms based on a JSON schema with automatic validation, navigation, and summary generation.
version: 0.0.2-dev
homepage: https://github.com/egovernments/health-campaign-field-worker-app/tree/master/packages/digit_forms_engine
repository: https://github.com/egovernments/health-campaign-field-worker-app
issue_tracker: https://github.com/egovernments/health-campaign-field-worker-app/issues
documentation: https://github.com/egovernments/health-campaign-field-worker-app/tree/master/packages/digit_forms_engine#readme

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  auto_route: ^8.3.0
  collection: ^1.16.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.1.0
  intl: ^0.19.0
  json_annotation: ^4.7.0
  reactive_forms: ^17.0.0
  digit_ui_components: ^0.2.2+7
  flutter_bloc: ^8.1.1
  uuid: ^4.5.1
  digit_scanner: ^1.0.6+2
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.1.1
  build_runner: ^2.2.1
  json_serializable: ^6.4.0
  bloc_test: ^9.1.0
  auto_route_generator: ^8.0.0

flutter: