targets:
  $default:
    builders:
      auto_route_generator:auto_route_generator:
        options:
        generate_for:
          - lib/**.dart
      auto_route_generator:auto_router_generator:
        generate_for:
          - lib/router/**router.dart