name: digit_data_converter
description: digit_data_converter is a Dart package designed to provide robust and flexible transformation of structured form data into Dart model objects. It supports advanced mapping configurations including nested objects, dynamic fields, and runtime-driven behavior.
version: 0.0.1-dev
homepage: https://github.com/egovernments/health-campaign-field-worker-app/tree/master/packages/digit_data_converter
repository: https://github.com/egovernments/health-campaign-field-worker-app

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  digit_data_model: ^1.2.0-dev.1-console
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


